name: Python compiler windows

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: clone repo
      uses: actions/checkout@v1
      with:
        submodules: 'true'
        
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow
        pip install pyinstaller  
      
    - name: python version
      run: python --version
    - name: pyinstaller version
      run: pyinstaller --version  

    - name: compile SSTviewer
      run: pyinstaller --noconsole .\src\SSTviewer.py

    - name: compile SSTviewer portable
      run: pyinstaller -F --noconsole .\src\SSTviewer.py      
            
    - name: save SSTviewer
      uses: actions/upload-artifact@master
      with:
        name: SSTviewer_windows
        path: .\dist\SSTviewer

    - name: save SSTviewer portable
      uses: actions/upload-artifact@master
      with:
        name: SSTviewer_windows_portable
        path: .\dist\SSTviewer.exe 
