name: Python compiler linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: clone repo
      uses: actions/checkout@v1
      with:
        submodules: 'true'
        
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow
        pip install pyinstaller
    - name: python version
      run: python --version
    - name: pyinstaller version
      run: pyinstaller --version
      
    - name: compile SSTviewer
      run: pyinstaller -F --noconsole ./src/SSTviewer.py

    - name: create DEB
      run: make

    - name: save SSTviewer deb
      uses: actions/upload-artifact@master
      with:
        name: SSTviewer_Linux_deb
        path: ./*.deb
